modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU GPLv3"
[[mods]]
modId = "htfc_subsidiaries"
version = "0.0.1"
displayName = "HTFC Subsidiaries"
displayURL = "https://github.com/thethirdswan/htfc_subsidiaries"
issueTrackerURL = "https://github.com/thethirdswan/htfc_subsidiaries/issues"
#logoFile="examplemod.png" #optional
authors = "The Third Swan"
displayTest = "MATCH_VERSION"
description = '''
Adds various QoL items for mods included in Hardrock TerraFirmaCraft!
'''
[[dependencies.htfc_subsidiaries]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.htfc_subsidiaries]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.htfc_subsidiaries]]
modId = "pneumaticcraft"
mandatory = true
versionRange = "[1.18.2-3.6.4-45,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.htfc_subsidiaries]]
modId = "tfc"
mandatory = true
versionRange = "[2.2.33,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.htfc_subsidiaries]]
modId = "compressedcreativity"
mandatory = true
versionRange = "[0.1.8,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.htfc_subsidiaries]]
modId = "tfcambiental"
mandatory = true
versionRange = "[2.0.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.htfc_subsidiaries]]
modId = "mekanism"
mandatory = true
versionRange = "[1.18.2-10.2.5.465,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.htfc_subsidiaries]]
modId = "immersiveengineering"
mandatory = true
versionRange = "[1.18.2-8.4.0-161,)"
ordering = "AFTER"
side = "CLIENT"
[[dependencies.htfc_subsidiaries]]
modId = "create"
mandatory = true
versionRange = "[0.5.1.e,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.htfc_subsidiaries]]
modId = "firmalife"
mandatory = true
versionRange = "[1.2.18,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.htfc_subsidiaries]]
modId = "tfc_ie_addon"
mandatory = true
versionRange = "[0.2.4,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.htfc_subsidiaries]]
modId = "tconstruct"
mandatory = true
versionRange = "[1.18.2-3.6.4.113,)"
ordering = "NONE"
side = "CLIENT"
# adding other mods' dependencies later, as long as it's not breaking *now*